version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on: [ zookeeper ]
    ports: [ "9092:9092" ]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # IMPORTANT: 29092 for Docker (internal), 9092 for Windows (external)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Fixes for single-node "Leader Not Available" errors:
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Flink Cluster
  jobmanager:
    build: .
    image: custom-flink-python
    ports: [ "8081:8081" ]
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./src:/opt/src
      - ./jars:/opt/flink/usrlib

  taskmanager:
    build: .
    image: custom-flink-python
    depends_on: [ jobmanager ]
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./src:/opt/src
      - ./jars:/opt/flink/usrlib

  # Your Python Scripts
  producer:
    build: .
    image: custom-flink-python
    depends_on: [ kafka ]
    # -u forces logs to show up immediately
    command: python -u /opt/src/producer.py
    volumes:
      - ./src:/opt/src
    restart: always

  job-submitter:
    build: .
    image: custom-flink-python
    depends_on: [ jobmanager, kafka ]
    environment:
      - DEMO_MODE=FALSE
    # Submits the job to the cluster
    command: >
      /opt/flink/bin/flink run -m jobmanager:8081 -py /opt/src/processor.py  --jarfile /opt/flink/usrlib/flink-sql-connector-kafka-3.0.1-1.18.jar
    volumes:
      - ./src:/opt/src
      - ./jars:/opt/flink/usrlib

  dashboard:
    build: .
    command: streamlit run /opt/src/dashboard.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - kafka
    volumes:
      - ./src:/opt/src

  alerter:
    build: .
    command: python -u /opt/src/alerter.py
    depends_on:
      - kafka
    volumes:
      - ./src:/opt/src
    restart: always
